DROP TABLE IF EXISTS PUBLIC.temp_s_min_level;
CREATE TABLE PUBLIC.temp_s_min_level AS 

SELECT    *,
		 (CASE WHEN "VENTAS_EN_VALOR_000000" = -1 THEN 0 ELSE "VENTAS_EN_VALOR_000000"*1000000 END) AS VENTAS_VALOR_nls,
		 (CASE WHEN "VENTAS_EN_VOLUMEN_KILOS_000" = -1 THEN 0 ELSE "VENTAS_EN_VOLUMEN_KILOS_000"*1000 END) AS VENTAS_VOLUMEN_nls
FROM PUBLIC.{mes}
WHERE "NOMBRE_ARCHIVO" IN ('NIELSEN_COLOMBIA_1_CAFE SOLUBLE_JUNIO2020.csv',
								 -- 'NIELSEN_COLOMBIA_1_CARNES FRIAS_JUNIO2020.csv',
								 -- 'NIELSEN_COLOMBIA_1_CEREALES EN BARRA_JUNIO2020.csv',
								 -- 'NIELSEN_COLOMBIA_1_CHOCOLATINAS_JUNIO2020.csv',
								 -- 'NIELSEN_COLOMBIA_1_HELADOS_JUNIO2020.csv',
							     'NIELSEN_COLOMBIA_1_MANI_JUNIO2020.csv')
/*AND ("NIVEL" = 'TAMANO'							    
OR ("DUP_CATEGORIA" = 'VEGETALES EN CONSERVA' AND "NIVEL" = 'RANGO')
OR ("DUP_CATEGORIA" = 'MODIFICADORES DE LECHE' AND "NIVEL" = 'NIVELDEAZUCAR'))
AND NOT ("NIVEL" = 'TAMANO' AND "DUP_CATEGORIA" = 'MODIFICADORES DE LECHE')*/
-- LIMIT 100
-- GROUP BY "NOMBRE_ARCHIVO"