DROP TABLE IF EXISTS PUBLIC.temp_04_rangos;
CREATE TABLE PUBLIC.temp_04_rangos AS 

SELECT '05'             AS "COD_FUENTE",	   
       a."FUENTE",
	   a."PERIODO_NLS",
	   a."AÑO",
	   a."MES",
	   a."FECHA",
	   a."MERCADO",
	   a."MERCADO_nls",
	   a."REGION",
	   a."CANAL",
	   a."producto" AS "PRODUCTO",
	   a."DES_PRODUCTO",
	   a."DESCRIPCION_nls",
	   a."CATEGORY",
	   a."SUBCATEGORY",
	   a."FABRICANTE",
	   a."MARCA",
	   a."SEGMENTO",
	   a."NEGOCIO",
	   a."FAMILIA",
	   a."SEGM_PRECIO",
	   a."SEGMENTO_TMLUC",
	   a."SUBCANAL",
	   a."ITEM",
	   a."OFERTA_PROMOCION" AS "OFERTAPROMOCION", 
	   a."SUBLINEA",
	   a."tiponeg" AS "TIPONEG",
	   a."TIPO",
	   a."forma" AS "FORMA",
	   a."familiaempaque" AS "FAMILIA_DE_EMPAQUE",
	   a."SABOR",
	   a."INTEGRALNOINTEGRAL",
	   a."SUBMARCA",	   
	   a."SUBTIPO",
	   a."linea" AS "LINEA",
	   a."VARIEDAD",
	   a."PRESENTACION",
	   a."segmento_noel" AS "SEGMENTO_NOEL",
	   a."SUBSEGMENTO_NOEL",
	   a."tiposalchicha" AS "TIPO_SALCHICHA",
	   a."EMPAQUE",
	   a."TIPODESABOR" AS "TIPO_SABOR", 
	   CASE WHEN a."TIPO_CARNE" = 'CERDO RES' THEN 'MIXTO' END AS "TIPO_CARNE",
	   -- "TIPO_CARNE",
	   a."NIVELDEAZUCAR",
	   a."CONSISTENCIA",
	   a."TAMANO_nls"			AS  "RANGOS",
	   '' 						AS  "BARCODE",
	   -- CASE WHEN a."TAMANO_nls_" = 0 THEN 'OTROS TAMANOS' ELSE a."TAMANO_nls_" || ' ' || 'GRS' END AS "TAMANO", 
	   CASE 
		WHEN a."NIVEL" = 'RANGO' THEN a."RANGO_SINPROC"
		WHEN a."NIVEL" = 'TAMANO' THEN a."TAMANO_SINPROC"
	   END	AS "TAMANO",
	   a."TAMANO_nls",
	   a."peso" AS "PESO",
	   a."UNIDAD",
	   a."factor_ajustes" 	AS "FACTOR",
	   a."precio_multiempaque" AS "PRECIO_MULTIEMPAQUE",
	   a."precio_unidad" AS "PRECIO_UNIDAD",
	   a."peso_individual" AS "PESO_INDIVIDUAL",
	   b."rango_precio" AS "RANGO_PRECIO",
	   a."precio_kilo" AS "PRECIO_KILO",
	   c."rango_precio_individual" AS "RANGO_PRECIO_INDIVIDUAL",
	   d."rango_tamano" AS "RANGO_TAMANO",
	   e."rango_tamano_individual" AS "RANGO_TAMANO_INDIVIDUAL",
	   a."VENTAS_VALOR_nls",
	   a."VENTAS_VOLUMEN_nls",
	   a."DIST_POND_nls",
	   a."DIST_NUM_nls",
	   a."mundos_shopper" AS "MUNDOS_SHOPPER"	   
FROM PUBLIC.temp_03_var_adi_rangos a
LEFT JOIN PUBLIC.temp_04_rango_precio b ON a.PRODUCTO = b.producto 
LEFT JOIN PUBLIC.temp_04_rango_precio_individual c ON a.PRODUCTO = c.producto 
LEFT JOIN PUBLIC.temp_04_rango_tamano d ON a.PRODUCTO = d.producto 
LEFT JOIN PUBLIC.temp_04_rango_tamano_individual e ON a.PRODUCTO = e.producto