DROP TABLE IF EXISTS PUBLIC.temp_s_min_level;
CREATE TABLE PUBLIC.temp_s_min_level AS 

SELECT *
FROM scantrack.{mes}
WHERE "NOMBRE_ARCHIVO" IN ('NIELSEN_COLOMBIA_2_CAFE SOLUBLE_JULIO2020.csv')
								 -- 'NIELSEN_COLOMBIA_1_CARNES FRIAS_JUNIO2020.csv',
								 -- 'NIELSEN_COLOMBIA_1_CEREALES EN BARRA_JUNIO2020.csv',
								 -- 'NIELSEN_COLOMBIA_1_CHOCOLATINAS_JUNIO2020.csv',
								 -- 'NIELSEN_COLOMBIA_1_HELADOS_JUNIO2020.csv',
							     -- 'NIELSEN_COLOMBIA_2_MANI_JULIO2020.csv')